### ISSUE TITLE
Support negative value

### ISSUE THREAD

**Issue by lavolpecheprogramma** [renatomoor/unocss-preset-fluid#6]
Hi,
thanks for your amazing work!
i would to ask you if it is possible to enable negative values (es. f-mx--12--32).

Thanks for your time!

**Comment by renatomoor** [comment]
Hello @lavolpecheprogramma 

I've added the support for negative values:

 - https://renatomoor.github.io/unocss-preset-fluid/examples/negative-positive-values.html
 - https://renatomoor.github.io/unocss-preset-fluid/examples/negative-values.html
 
Thanks for your idea!
