### ISSUE TITLE
Documentation out of date or padding-right rule missing

### ISSUE THREAD

**Issue by SparkmanDesigns** [renatomoor/unocss-preset-fluid#8]
[According to the documentation](https://renatomoor.github.io/unocss-preset-fluid/utilities.html), the `f-pr` utility is meant to calculate `padding-right`.

But `padding-right` rule is missing in [src/utilities.ts](https://github.com/renatomoor/unocss-preset-fluid/blob/main/src/utilities.ts).

And the UnoCSS VSCode extension doesn't pick it up:
![image](https://github.com/renatomoor/unocss-preset-fluid/assets/53072187/24c426ba-1400-41f9-8b62-f96b3f03d78e)

(Great preset, btw! Really seamless in both functionally and visually within layouts.)

**Comment by renatomoor** [comment]
Hello @SparkmanDesigns !
Thanks a lot for you input.

I just fix it in the release https://github.com/renatomoor/unocss-preset-fluid/releases/tag/1.0.1

Have a good day and thanks again for your contribution!
